version: '3.8'

services:
  app:
    container_name: wwebjs_api
    build: . # Enable local build
    # image: avoylenko/wwebjs-api:latest # Comment out pre-built image if building locally
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Environment variables from .env will override these if they conflict,
      # but it's good to list essential ones or defaults if .env is missing for some reason.
      # Values in .env will take precedence.
      # - API_KEY=your_global_api_key_here  # OPTIONAL - Define in .env
      - BASE_WEBHOOK_URL=http://localhost:3000/localCallbackExample # Can be in .env
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION - Can be in .env
      - MAX_ATTACHMENT_SIZE=5000000 # IN BYTES
      - SET_MESSAGES_AS_SEEN=TRUE # WILL MARK THE MESSAGES AS READ AUTOMATICALLY
      # ALL CALLBACKS: auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed
      - DISABLED_CALLBACKS=message_ack|message_reaction  # PREVENT SENDING CERTAIN TYPES OF CALLBACKS BACK TO THE WEBHOOK
      - ENABLE_SWAGGER_ENDPOINT=TRUE # OPTIONAL, ENABLES THE /api-docs ENDPOINT - Can be in .env
      # - RATE_LIMIT_MAX=1000 # OPTIONAL, THE MAXIUM NUMBER OF CONNECTIONS TO ALLOW PER TIME FRAME
      # - RATE_LIMIT_WINDOW_MS=1000 # OPTIONAL, TIME FRAME FOR WHICH REQUESTS ARE CHECKED IN MS
      # - WEB_VERSION='2.2328.5' # OPTIONAL, THE VERSION OF WHATSAPP WEB TO USE
      # - WEB_VERSION_CACHE_TYPE=none # OPTIONAL, DETERMINES WHERE TO GET THE WHATSAPP WEB VERSION(local, remote or none), DEFAULT 'none'
      # - RECOVER_SESSIONS=TRUE # OPTIONAL, SHOULD WE RECOVER THE SESSION IN CASE OF PAGE FAILURES
      # Explicitly add new auto-reply ENV vars here as well, though .env takes precedence
      - ENABLE_AUTO_REPLY=${ENABLE_AUTO_REPLY:-false} # Defaults to false if not in .env
      - AUTO_REPLY_MESSAGE=${AUTO_REPLY_MESSAGE:-Default auto reply if not set in .env}
      - ENABLE_AI_AGENT=${ENABLE_AI_AGENT:-true} # Defaults to true if not in .env
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Defaults to true if not in .env
      - TAVILY_API_KEY=${TAVILY_API_KEY} # Defaults to true if not in .env
    volumes:
      - ./sessions:/usr/src/app/sessions # Mount the local ./sessions/ folder to the container's /usr/src/app/sessions folder
      # - ./:/usr/src/app # Mount the local source code for development
